/*************** Museum info set in local storage *****************************/
// American Museum of Natural History
localStorage.museum1 = '<section class="museumContent" id="amnh"><div class="title museList manhattan sunday monday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="amnhBox" id="amnhBox"><label></label></div><a href="#">American Museum of Natural History</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 10am-5:45pm<br>Monday: 10am-5:45pm<br>Tuesday: 10am-5:45pm<br>Wednesday: 10am-5:45pm<br>Thrusday: 10am-5:45pm<br>Friday: 10am-5:45pm<br>Saturday: 10am-5:45pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><b>Discount</b>:<br>Suggested donation, at museum ticket counter only.</section></div></div></p></div></section>';
// Bronx Museum of the Arts
localStorage.museum2 = '<section class="museumContent" id="bronxMuseum"><div class="title museList bronx sunday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="bronxMuseumBox" id="bronxMuseumBox"><label></label></div><a href="#">Bronx Museum of the Arts</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 11am-6pm<br>Wednesday: 1pm-6pm<br>Thrusday: 11am-6pm<br>Friday: 11am-8pm<br>Saturday: 11am-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Bronx</section><section class="last"><b>Discount</b>:<br>Museum is free to everyone.</section></div></div></p></div></section>';
// Brooklyn Museum
localStorage.museum3 = '<section class="museumContent" id="brooklynMuseum"><div class="title museList brooklyn sunday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="brooklynMuseumBox" id="brooklynMuseumBox"><label></label></div><a href="#">Brooklyn Museum</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 11am-6pm<br>Wednesday: 11am-6pm<br>Thrusday: 11am-10pm<br>Friday: 11am-6pm<br>Saturday: 11am-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Brooklyn</section><section class="last"><b>Discount</b>:<br>Suggested donation at museum ticket counter only. First Saturday of the month (except September) is free and includes events at the museum.</section></div></div></p></div></section>';
// Metropolitan Museum of Art
localStorage.museum4 = '<section class="museumContent" id="metMuseum"><div class="title museList manhattan sunday monday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="metMuseumBox" id="metMuseumBox"><label></label></div><a href="#">Metropolitan Museum of Art</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 10am-5:30pm<br>Monday: 10am-5:30pm<br>Tuesday: 10am-5:30pm<br>Wednesday: 10am-5:30pm<br>Thrusday: 10am-5:30pm<br>Friday: 10am-9pm<br>Saturday: 10am-9pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><b>Discount</b>:<br>Suggested donation for New York residents. <br>General Admission tickets are valid for three consecutive days at the Met Fifth Avenue, The Met Breuer, and The Met Cloisters.</section></div></div></p></div></section>';
// The Morgan Library & Museum
localStorage.museum5 = '<section class="museumContent" id="morganMuseum"><div class="title museList manhattan sunday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="morganMuseumBox" id="morganMuseumBox"><label></label></div><a href="#">The Morgan Library and Museum</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 11am-6pm<br>Tuesday: 10:30am-5pm<br>Wednesday: 10:30am-5pm<br>Thrusday: 10:30am-5pm<br>Friday: 10:30am-9pm<br>Saturday: 10am-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><b>Discount</b>:<br>   Admission is free on Fridays from 7 p.m. to 9 p.m.<br>Admission to the McKim rooms only is free during the following times: Tuesday, 3pm to 5pm; Friday, 7pm to 9pm; Sunday, 4pm to 6pm.</section></div></div></p></div></section>';
// Museum of Chinese in America
localStorage.museum6 = '<section class="museumContent" id="moca"><div class="title museList manhattan sunday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="mocaBox" id="mocaBox"><label></label></div><a href="#">Museum of Chinese in America</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 11am-6pm<br>Tuesday: 11am-6pm<br>Wednesday: 11am-6pm<br>Thrusday: 11am-9pm<br>Friday: 11am-6pm<br>Saturday: 11am-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><b>Discount</b>:<br>Gallery addmission is free every first Thursday except on holidays.</section></div></div></p></div></section>';
// Museum of the Moving Image
localStorage.museum7 = '<section class="museumContent" id="momi"><div class="title museList queens sunday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="momiBox" id="momiBox"><label></label></div><a href="#">Museum of the Moving Image</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 10:30am-6pm<br>Wednesday: 10:30am-5pm<br>Thrusday: 10:30am-5pm<br>Friday: 10:30am-8pm<br>Saturday: 10:30am-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Queens</section><section class="last"><b>Discount</b>:<br>Free addmission on Fridays from 4pm-8pm.</section></div></div></p></div></section>';
// Nicholas Roerich Museum
localStorage.museum8 = '<section class="museumContent" id="roerichMuseum"><div class="title museList manhattan sunday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="roerichMuseumBox" id="roerichMuseumBox"><label></label></div><a href="#">Nicholas Roerich Museum</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 2pm-5pm<br>Tuesday: 12pm-4pm<br>Wednesday: 12pm-4pm<br>Thrusday: 12pm-4pm<br>Friday: 12pm-4pm<br>Saturday: 2pm-5pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><b>Discount</b>:<br>Free addmission.<br> Concerts on most Sundays at 5pm.</section></div></div></p></div></section>';
// Staten Island Museum
localStorage.museum9 = '<section class="museumContent" id="statenMuseum"><div class="title museList staten sunday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="statenMuseumBox" id="statenMuseumBox"><label></label></div><a href="#">Staten Island Museum</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 11am-5pm<br>Wednesday: 11am-5pm<br>Thrusday: 11am-5pm<br>Friday: 11am-5pm<br>Saturday: 11am-5pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Staten Island</section><section class="last"><b>Discount</b>:<br>Suggested donation.</section></div></div></p></div></section>';
// Studio Museum
localStorage.museum10 = '<section class="museumContent" id="studioMuseum"><div class="title museList manhattan sunday monday tuesday wednesday thursday friday saturday"><div class="ui right checkbox"><input type="checkbox" name="studioMuseumBox" id="studioMuseumBox"><label></label></div><a href="#">Studio Museum</a></div><div class="content"><p class="transition hidden"><div class="ui two column grid"><div class="column"><b>Days</b>:<br>Sunday: 12pm-6pm<br>Monday: 12pm-6pm<br>Tuesday: 12pm-6pm<br>Wednesday: 12pm-6pm<br>Thrusday: 12pm-6pm<br>Friday: 12pm-6pm<br>Saturday: 12pm-6pm<br></div><div class="column"><section class="borough"><b>Borough</b>:<br>Manhattan</section><section class="last"><br>  *the Studio Museum galleries are closed during the construction of their new facilities, projected to continue through 2021</section></div></div></div></p></div></section>';

document.getElementById("customList1").innerHTML = localStorage.getItem("museum1") + localStorage.getItem("museum2") + localStorage.getItem("museum3") + localStorage.getItem("museum4") + localStorage.getItem("museum5") + localStorage.getItem("museum6") + localStorage.getItem("museum7") + localStorage.getItem("museum8") + localStorage.getItem("museum9") + localStorage.getItem("museum10");

function setCookie(listName1, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
    var expires = "expires="+d.toUTCString();
    var cvalue = getElementById('listName1').value;
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}